### ISSUE TITLE
Magical Activator dup bug

### ISSUE THREAD

**Issue by Nonsanity** [Modbder/EssentialCraft3#13] opened 2015-07-18 07:54 UTC
In the Magical Activator, damage value 5 (with all modifications), if an item is placed in the lower-right slot of the 3x3 grid and the mouse moves across/over it, the item will be duplicated into the top-left slot of the grid. It can be removed and the process repeated for unlimited duplication

**Comment by Modbder** [comment] 2015-07-19 10:11
I can't reproduce the issue - could you attach a screenshot?

**Comment by Eidelmaim** [comment] 2015-09-01 15:42
i can not replicate it either... what item are you putting in the activator and what version of EC3 are you using ?

**Comment by Nonsanity** [comment] 2015-09-02 19:39
Though I'm still using the same version, 4.5.1710.208 (not the latest, I know), I can't duplicate it either. Instead, I'm seeing the camouflage slot being the same as the second slot in the 3x3 inventory. But that doesn't seem to lead to duplication.

The following screenshot shows 8 orange wool and only 1 red wool. I can remove the red wool from either place, but it doesn't duplicate. (The other red wool disappears.)

![screen shot 2015-09-02 at 3 37 34 pm](https://cloud.githubusercontent.com/assets/3012708/9642166/99f35908-5188-11e5-9b1c-efd316b6d232.png)

**Comment by Modbder** [comment] 2015-09-03 08:37
That was fixed in 4.6.1710.42(the red wool glitch). I just want to make sure there is no duplication with the device.

**Comment by Modbder** [comment] 2015-10-03 09:43
So, since I can't really replicate the issue, and it seems like you can't either I am going to close this for now. Feel free to open it if you find a way to replicate it.

**Closed as completed** 2015-10-03 09:44 UTC
Labels: bug, Will be fixed, More info needed, Can't replicate
